apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-command-central
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-command-central
  template:
    metadata:
      labels:
        app: ubuntu-command-central
    spec:
      securityContext:
        runAsUser: 0  # Run as root to modify /etc/shadow and generate SSH keys
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: ubuntu-command-central
        image: harbor.mr-elamin.com/library/ubuntu-command-central:24.04  # Correct image name and tag
        imagePullPolicy: IfNotPresent  # Ensure the image is pulled only if not present
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /backup
          name: mariadb-db-backup
        env:
        - name: MARIADB_ROOT_PASSWORD         # Environment variable for MariaDB root password
          valueFrom:
            secretKeyRef:
              name: mariadb-credentials
              key: mariadb-root-password
        - name: ROOT_PASSWORD         # Environment variable for system root password
          valueFrom:
            secretKeyRef:
              name: user-passwords
              key: root-password
        - name: PATH
          value: "/opt/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        securityContext:
          allowPrivilegeEscalation: true  # Allow privilege escalation
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: false
        command: ["/usr/local/bin/startup.sh"]
      volumes:
      - name: mariadb-db-backup
        persistentVolumeClaim:
          claimName: mariadb-db-backup
      restartPolicy: Always